// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb-_EWIguIQrX1H6SUQQu4QML_aRi4pIc',
    appId: '1:701159381264:web:24bd303d1938cf10586d95',
    messagingSenderId: '701159381264',
    projectId: 'be-real-2c921',
    authDomain: 'be-real-2c921.firebaseapp.com',
    storageBucket: 'be-real-2c921.firebasestorage.app',
    measurementId: 'G-N2KJ5PGPHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32xbMPF4ID2C8eJRDTl6_frMUBPySzt0',
    appId: '1:701159381264:android:01b875af9be25f4b586d95',
    messagingSenderId: '701159381264',
    projectId: 'be-real-2c921',
    storageBucket: 'be-real-2c921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAM4dWazesI3oycKjTeWeiUD3EHCEAyKk',
    appId: '1:701159381264:ios:fe962d4dc548eb5d586d95',
    messagingSenderId: '701159381264',
    projectId: 'be-real-2c921',
    storageBucket: 'be-real-2c921.firebasestorage.app',
    iosBundleId: 'com.example.beReal',
  );
}
